// This file is the main layout for the application
// defines the HTML structure and global settings that applies to all pages
// to define the metadata for each page (better for SEO-search engine optimization)
import type { Metadata } from "next";

// importing Inter google font
import { Inter } from "next/font/google";

// neat for combining class names
import { cn } from "@/lib/utils";
// for query management (allows you to fetch, cache, and update data easily without having to manage the state manually)
import { QueryProvider } from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";

// importing global styles
import "./globals.css";

// creating an instance of the Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// metadata for the application
// this metadata is used for SEO and other purposes
export const metadata: Metadata = {
  title: "Agile Task App",
  description: "Generated by create next app",
};

// RootLayout component is the main layout for the application
// children prop is used to render the content of each page 
// readonly type is used to ensure that the children prop is not modified
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
      >
        {/* QueryProvider is used to provide the query client to the application */}
        {/* This allows you to use the useQuery and useMutation hooks in your components */}
        <QueryProvider>
          <Toaster />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
